services:
  mysql:
    image: mysql:8.0
    container_name: urbanchain_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urbanchain
      MYSQL_USER: urbanchain
      MYSQL_PASSWORD: urbanchain
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ipfs:
    image: ipfs/kubo:latest
    container_name: urbanchain_ipfs
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8081:8080"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

volumes:
  mysql_data:
  ipfs_staging:
  ipfs_data:
